### ISSUE TITLE
Solo mining error

### ISSUE THREAD

**Issue by kayson9** [DevelCurrency/SPAC_Coin#2]
I got the miner from pooler/cpuminer. Running command is
minerd.exe -a scrypt -o http://127.0.0.1:38038 -O u:p
it return error: 500 internal error
json_rpc_call failed.

config file:
server=1
listen=1
daemon=1
rpcuser=u
rpcpassword=p
rpcallowip=127.0.0.1
rpcport=38038
port=38037
gen=0

Do u have any ideal ?

**Comment by DevelCurrency** [comment]
SPAC Coin - pure PoS!
